services:
  - type: web
    name: codequest-api
    runtime: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: ENV_MODE
        value: production
      - key: USE_SQLITE
        value: "true"
      - key: SECRET_KEY
        generateValue: true
